version: "3"
services:
  rolls-svc:
    container_name: rolls-svc
    build:
      context: .
      target: production
    command: node ./build/app.js
    environment:
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"

networks:
  default:
    name: getaccept_default
    external: true