version: "3"
services:
  rolls-svc:
    container_name: rolls-svc
    build:
      context: .
      target: install
    command: npm run dev
    volumes:
      - ./src:/app/src
      - ./types:/app/types
    environment:
      NODE_ENV: development
      PORT: 3000
      AWS_ENDPOINT_URL: http://localstack:4566
    ports:
      - "8083:3000"
    networks:
      - getaccept_default

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
    volumes:
      - "~/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - getaccept_default

networks:
  getaccept_default:
    name: getaccept_default
    external: true