version: "3"
services:
  rolls-svc:
    container_name: rolls-svc
    build:
      context: .
      target: install
    command: npm run dev
    volumes:
      - ./src:/app/src
      - ./types:/app/types
    environment:
      NODE_ENV: development
      PORT: 3000
      AWS_ENDPOINT_URL: http://localstack:4566
    ports:
      - "8083:3000"

networks:
  default:
    name: getaccept_default
    external: true