version: "3"
services:
  calculator-svc:
    container_name: calculator-svc
    build:
      context: .
      target: install
    command: npm run dev
    volumes:
      - ./src:/app/src
      - ./types:/app/types
    environment:
      NODE_ENV: development
      PORT: 3000
      AWS_ENDPOINT_URL: http://localstack:4566
    ports:
      - "8081:3000"
    networks:
      - getaccept_default

networks:
  getaccept_default:
    name: getaccept_default
    external: true